<?php $form->prepare() ?>

        <h3><?= $this->translate('Site Title') ?></h3>
        <?= $this->form()->openTag($form) ?>

            <div class="form-group">
                <?= $this->formRow($form->get('logo')) ?>

                <p class="help-block"><?= $this->translate('You can use placeholders: {theme_images} and {uploads}') ?></p>

            </div>
            <div class="form-group">
                <?= $this->formRow($form->get('title')) ?>

            </div>
            <div class="form-group">
                <?= $this->formbutton($form->get('save')) ?>

            </div>

        <?= $this->form()->closeTag($form) ?>
